### ISSUE TITLE
There is no way to craft stripped bamboo

### ISSUE THREAD

**Issue by JalapenoGremlin** [moddingplayground/twigs-fabric#15]
There does not appear to be any way to obtain stripped bamboo in survival. 

There is no crafting recipe and "using" an axe/sword on a bamboo plant or bamboo bundle (like how logs are stripped) does not crate stripped bamboo. 

How does one craft stripped bamboo to make the "stripped bamboo" items in Survival?

**Comment by dvitski** [comment]
In the latest release, you can stonecut bamboo to get stripped bamboo :)

**Comment by JalapenoGremlin** [comment]
Thank you!  That did it. 

I didn't think of the stone cutter.
