### ISSUE TITLE
Frame API not listed in "Relations" tab in dependencies in CurseForge

### ISSUE THREAD

**Issue by Godols** [moddingplayground/twigs-fabric#18]
Title speaks for itself. Downloaded the beta7.0 for 1.19 which took a bit of tinkering to figure out what "frame version 0.21 is needed" meant. Thankfully found out what I needed to download thanks to the Fabric Discord. Don't know if this is voluntary or not considering the 1.19 mod is in beta, but idk i'm not making the mod and just downloaded one version of it.

**Comment by dvitski** [comment]
It's listed here on the file itself:

![image](https://user-images.githubusercontent.com/36608902/177413398-5791c04b-17ba-4a11-982c-779bb3a07745.png)


I assume it'll be listed here when it's not marked as beta:
![image](https://user-images.githubusercontent.com/36608902/177413459-b1f3cb4b-9d3f-42b3-b831-cebf407e02f7.png)

**Comment by Godols** [comment]
Apologize then. Thanks for pointing it out though! Will help for different mods to check when I have no clue what to get.
