### ISSUE TITLE
No work on Quilt 1.19.2

### ISSUE THREAD

**Issue by Kuggle01** [moddingplayground/twigs-fabric#22]
![image](https://user-images.githubusercontent.com/77563171/188021573-31af5f80-4fdb-4359-af2c-b55c15315133.png)
When trying to load this mod on Quilt 1.19.2 it comes up with this error, I have no idea why and cannot discern a solotion besides just removing twigs 
https://paste.ee/p/fiA3w

**Comment by dvitski** [comment]
**You need to install [Frame](https://www.curseforge.com/minecraft/mc-mods/frame-api)**

~~Furthermore, Quilt is not supported by Twigs :p~~
~~Frame also doesn't work on Quilt - for technical reasons it literally will not run from startup, this may be fixed in one way or another in the future 🙂~~

**Comment by ghost** [comment]
> Frame also doesn't work on Quilt

Works fine for me

**Comment by dopadream** [comment]
yeah twigs works on quilt for me idk

**Comment by dopadream** [comment]
make sure you're using QFAPI

**Comment by dvitski** [comment]
I'm surprised to find that this does in fact work on Quilt now, nice!
