### ISSUE TITLE
Ability to disable Seashells

### ISSUE THREAD

**Issue by ghost** [moddingplayground/twigs-fabric#28]
I use Twigs in combination with [Ecologics](https://www.curseforge.com/minecraft/mc-mods/ecologics), which also adds seashells. While seashells can be disabled in Ecologics, it'd be preferable to disable them in Twigs as, in Ecologics, they are used for crafting.

Thanks!

**Comment by dvitski** [comment]
Data pack to disable spawning: [disable_sea_shells.zip](https://github.com/moddingplayground/twigs-fabric/files/9793958/disable_sea_shells.zip)
