### ISSUE TITLE
[Crash] [1.18.2] Minecraft wont load up after adding Twigs

### ISSUE THREAD

**Issue by xR4YM0ND** [moddingplayground/twigs-fabric#3]
Hey there, 

so im making this modpack with lots of mods and it seems like twigs is crashing. "Wont even load the game"

Fabric 1.18.2 - 0.13.3

[Latest.Log](https://gist.github.com/SpigotDE/3d94c10f2071d48bf0070cbfc56b0e81)
[Crash Report Server](https://gist.github.com/SpigotDE/06656d3d355456c7db4ecf3d53dcf6de)
[Crash Report Client](https://gist.github.com/SpigotDE/3a242b6574d680249c0e991a08a92933)

**Comment by dvitski** [comment]
_Relates to #2_

We're working on a 2.0 release that will likely come soon™️, and it's likely that this crash is probably fixed in that
I'm not going to look into this currently as it wouldn't be worth it at the moment, apologies

**Comment by xR4YM0ND** [comment]
ok i will test this out and let you know

**Comment by dvitski** [comment]
I lied
