### ISSUE TITLE
Translation Support

### ISSUE THREAD

**Issue by IceDragonFla** [moddingplayground/twigs-fabric#30]
Hello, thank u for developing this awesome mod. Many things in this mod really colorful my world.
Importantly, Im a Chinese player, when I playing with my friends, English is not availble for them.
So I want to translate this mod into Chinese.
If I can do it, I will translate it for days and upload the lang file.
Best wishes,
CrystalYan

e-mail: mrcrystalyan@163.com

**Comment by dvitski** [comment]
Thank you! Please make a pull request at [N1nn1/twigs](https://github.com/N1nn1/twigs/pulls)
