### ISSUE TITLE
[Oddly Specific Issue] Splash Text Isn't Hidden Properly

### ISSUE THREAD

**Issue by ghost** [moddingplayground/twigs-fabric#35]
Hi, so I'm having an oddly specific problem that will probably not be relevant to anyone else, but I wanted to ask for help anyway. I'm using [MinimalMenu](https://modrinth.com/mod/minimalmenu) to hide the splash text on the Minecraft title screen, but either Twigs or Frame API is causing it to render again.

![Untitled](https://user-images.githubusercontent.com/108554062/227843458-89d88de5-a324-4a69-b89f-ba769578f27c.png)

The only splash text ever shown is "Why no chairs?" and this problem is resolved by removing Twigs and Frame API from my modpack. Is one of these 2 mods doing something invasive with the splash text handling? I also tried looking through the assets for both mods and their built-in libraries, but could find nothing related to splash texts that I could easily fix myself.

**Comment by dvitski** [comment]
Fixed in the latest version of Twigs (the feature was removed)

https://www.curseforge.com/minecraft/mc-mods/twigs/files
