### ISSUE TITLE
Fabric / Crash on Startup

### ISSUE THREAD

**Issue by ground-fruit** [moddingplayground/twigs-fabric#38]
I *think* there is an incompatibility with [every compat](https://modrinth.com/mod/every-compat)

Minecraft 1.19.2
Fabric 0.14.19
Twigs 3.0.0

[crash-2023-05-10_18.36.55-client.txt](https://github.com/moddingplayground/twigs-fabric/files/11446736/crash-2023-05-10_18.36.55-client.txt)

**Comment by dvitski** [comment]
Duplicate of #37, thank you for the Fabric report though :)
