### ISSUE TITLE
Looking into causes of a specific mixin error, I found this

### ISSUE THREAD

**Issue by Sunconure11** [moddingplayground/twigs-fabric#5]
https://pastebin.com/Yk5j52rL

**Comment by dvitski** [comment]
This crash is caused when registering the Twigs item group, which calls off a bunch of Fabric API methods using mixins out of Twigs' control
You seem to have some kind of mod incompatibility it seems, as my best guess?

**Comment by Sunconure11** [comment]
I found the mod responsible for this error.

**Comment by dvitski** [comment]
Alrighty!
