### ISSUE TITLE
[Bug?] Pebbles replacing inventory items in creative mode

### ISSUE THREAD

**Issue by dewwdrp** [moddingplayground/twigs-fabric#6]
As the title says, sometimes I go into creative mode in a survival world because well, I'm too impatient for some things, anyways. I'm posting here because a couple of times now I've been shuffling things around in my inventory, and I use a backpack mod, well I right click on the backpack to open it, but I just so happen to also be pointing at a block with a pebble on it as well without noticing. Until I finish the right click and now my backpack is not open. It's been replaced by a pebble. Completely. It didn't move the backpack to another inventory slot when I have like 20 slots open, it completely replaced the backpack. I of course tested this out with vanilla items as well to make sure it wasn't because it was a modded item and the pebbles also completely replace vanilla things like pistons, swords, dirt blocks, etc...

It's not an issue at all in survival thankfully, but having a whole backpack full of stuff lost to the void with no way of getting it back is a little disheartening, as I kind of lost everything I had in that save, since I hadn't settled down yet. I'm running the latest version of the mod 1.1.3 for 1.18.1 on Fabric, so I know that's probably not in your focus anymore, you've probably shifted focus to 1.18.2, but I thought I'd let you know anyways, just in case.

Also thank you for sharing your hard work with us, I really do love this mod.

**Comment by dvitski** [comment]
Thanks for the detailed issue! Pebbles being able to be picked up like this will be removed in the next major release, so I'm not going to worry about this too much. Just be really careful for a bit :)
