### ISSUE TITLE
Formatting issue on newer builds of Fabric

### ISSUE THREAD

**Issue by Sunconure11** [moddingplayground/twigs-fabric#7]
https://pastebin.com/tYNqP6dz

**Comment by dvitski** [comment]
`FormattedException` thrown by Not Enough Crashes, as opposed to a formatting issue :)

The actual thrown exception, here:
> Caused by: net.fabricmc.loader.impl.util.ExceptionUtil$WrappedException: net.fabricmc.loader.impl.util.UrlConversionException: java.net.MalformedURLException: unknown protocol: magic-at

...appears to be thrown by [Fabric-ASM](https://github.com/Chocohead/Fabric-ASM), used by both [Farmer's Delight](https://bitbucket.org/n-horyzon/farmers-delight-fabric) and [Craft Tweaker](https://github.com/CraftTweaker/CraftTweaker).

This crash occurs when Twigs is registering its item group (practically the same as #5), so Twigs \*shouldn't\* be responsible for this crash.

**Comment by dvitski** [comment]
Stale
